# Generated by Django 5.1.4 on 2025-01-05 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('roster', '0003_remove_shift_description_remove_shift_is_holiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_profile',
            name='shift',
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roster.shift'),
        ),
    ]
