# Generated by Django 5.1.4 on 2025-01-05 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_employee_profile_shift_user_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reports_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
