# Generated by Django 5.1.4 on 2025-01-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_reports_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
