# Generated by Django 5.1.4 on 2025-01-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_holiday_alter_shift_options_shift_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_holiday',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
