# Generated by Django 5.1.4 on 2025-01-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_remove_shift_description_remove_shift_is_holiday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
    ]
