# Generated by Django 5.1.4 on 2025-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_alter_shift_options_remove_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
    ]
